services:
  proxy:
    build: ./
    ports:
      - 8000:80
      - 443:443
    restart: unless-stopped

  web:
    build: ./integration/upstream
    deploy:
      replicas: 4
    restart: unless-stopped
